Repository napzakmarket/Napzak-Android, pull requests merged in 2025-07, with the labels that each got.

#268 [UI/#267] 로딩 오버레이 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/NapzakLoadingOverlay.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
Labels: UI :iphone:, 암살자석준 :rage:

#270 [UI/#269] 담당화면 로딩뷰 적용
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/NapzakLoadingOverlay.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/topbar/NavigateUpTopBar.kt
  core/designsystem/src/main/res/drawable/ic_chevron_left_24.xml
  core/designsystem/src/main/res/drawable/ic_chevron_right.xml
  feature/detail/src/main/java/com/napzak/market/detail/component/bottombar/ProductDetailBottomBar.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductMarketGroup.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/component/MyPageProfileSection.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/state/MyPageUiState.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/navigation/SignOutNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/withdraw/WithdrawConfirmScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/withdraw/WithdrawViewModel.kt
  feature/report/src/main/java/com/napzak/market/report/ReportScreen.kt
  feature/report/src/main/java/com/napzak/market/report/ReportViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/state/EditStoreUiState.kt
  feature/store/src/main/java/com/napzak/market/store/model/Product.kt
Labels: UI :iphone:, 암살자석준 :rage:

#276 [UI/#271] 이미지 확대 화면에 스크롤 기능 추가
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/image/ZoomableImageScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductImageGroup.kt
Labels: UI :iphone:, 암살자석준 :rage:

#281 [FEAT/#260] 채팅 메세지 목록 조회 API 연결
  app/build.gradle.kts
  data/chat/build.gradle.kts
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatRoomDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/di/RepositoryModule.kt
  data/chat/src/main/java/com/napzak/market/chat/di/ServiceModule.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomInformationResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomListResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomMessagesResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomInformationMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRoomRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatRoomService.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatService.kt
  data/chat/src/test/java/com/napzak/market/chat/ApiAbstract.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomListApiTest.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomMessagesApiTest.kt
  data/chat/src/test/resources/api-response/ChatRoomList.json
  data/chat/src/test/resources/api-response/ChatRoomMessages.json
  data/remote/build.gradle.kts
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/remote/src/main/java/com/napzak/market/remote/qualifier/NetworkQualifier.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatItem.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatRoom.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatRoomInformation.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ProductBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/StoreBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRepository.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRoomRepository.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#280 [FEAT/#260] 채팅방 API 연결
  app/build.gradle.kts
  data/chat/.gitignore
  data/chat/build.gradle.kts
  data/chat/consumer-rules.pro
  data/chat/proguard-rules.pro
  data/chat/src/main/AndroidManifest.xml
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatRoomDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/di/RepositoryModule.kt
  data/chat/src/main/java/com/napzak/market/chat/di/ServiceModule.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomCreateRequest.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomCreateResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomEnterResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomInformationResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomListResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomMessagesResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomPatchProductRequest.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomPatchProductResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomInformationMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRoomRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatRoomService.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatService.kt
  data/chat/src/test/java/com/napzak/market/chat/ApiAbstract.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomInformationApiTest.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomListApiTest.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomMessagesApiTest.kt
  data/chat/src/test/resources/api-response/ChatRoomInformation.json
  data/chat/src/test/resources/api-response/ChatRoomList.json
  data/chat/src/test/resources/api-response/ChatRoomMessages.json
  data/remote/build.gradle.kts
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/remote/src/main/java/com/napzak/market/remote/qualifier/NetworkQualifier.kt
  domain/chat/.gitignore
  domain/chat/build.gradle.kts
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatItem.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatRoom.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatRoomInformation.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ProductBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/StoreBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRepository.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRoomRepository.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT :sparkles:, 암살자석준 :rage:

#272 [FEAT/#254] 푸시 알림 구현
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/napzak/market/config/messaging/NapzakFirebaseMessaging.kt
  app/src/main/java/com/napzak/market/config/messaging/NotificationClickReceiver.kt
  app/src/main/res/drawable/ic_push_notification.xml
  build.gradle.kts
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/main/src/main/java/com/napzak/market/main/ChatDeepLinkEventBus.kt
  feature/main/src/main/java/com/napzak/market/main/MainActivity.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#288 [UI/#273] 로딩뷰 적용
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/loading/NapzakLoadingOverlay.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/loading/NapzapLoadingSpinnerOverlay.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/withdraw/WithdrawConfirmScreen.kt
  feature/report/src/main/java/com/napzak/market/report/ReportScreen.kt
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
Labels: UI :iphone:, 충신채린 :saluting_face:

#289 [UI/#285] 구해요/팔아요 로딩 화면 추가
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
Labels: UI :iphone:, 퍼시벌종명 :sunglasses:

#259 [REFACTOR/#243] ContentUriRequestBody를 개선
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/ImageCompressor.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepositoryImpl.kt
  data/remote/src/main/java/com/napzak/market/remote/ContentUriRequestBody.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepository.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/ClearCacheUseCase.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/CompressImageUseCase.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/GetProductPresignedUrlUseCase.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/UploadImageUseCase.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoContainer.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoPicker.kt
  feature/registration/src/main/java/com/napzak/market/registration/model/Photo.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
Labels: REFACTOR :recycle:, 퍼시벌종명 :sunglasses:

#291 [UI/#287] 온보딩 장르 검색 로딩뷰 적용
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreUiState.kt
Labels: UI :iphone:, 멀린연진 :angel:

#296 [UI/#294] 홈화면 하단에 푸터 추가
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakLargeProductItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakSmallProductItem.kt
  core/designsystem/src/main/res/drawable/ic_footer_instagram.xml
  core/designsystem/src/main/res/drawable/ic_footer_mail.xml
  core/ui_util/src/main/java/com/napzak/market/ui_util/ContextExt.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/HomeViewModel.kt
  feature/home/src/main/java/com/napzak/market/home/component/HomeFooter.kt
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalAutoScrollableImages.kt
  feature/home/src/main/java/com/napzak/market/home/state/HomeUiState.kt
  feature/home/src/main/res/values/strings.xml
Labels: UI :iphone:, 암살자석준 :rage:

#292 [FEAT/#284] 채팅 목록 화면 로직 구현
  .gitignore
  data/chat/src/main/java/com/napzak/market/chat/client/ChatSocketClient.kt
  data/chat/src/main/java/com/napzak/market/chat/client/ChatSocketClientImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatRoomDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/datasource/ChatSocketDataSource.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatMessageMetadata.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomListResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRoomRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatSocketRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatRoomService.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomInformationApiTest.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomListApiTest.kt
  data/chat/src/test/resources/api-response/ChatRoomList.json
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRepository.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRoomRepository.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatSocketRepository.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/component/ChatRoomItem.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/WebSocketLifecycleObserver.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:
