Repository napzakmarket/Napzak-Android, pull requests merged in 2025-08, with the labels that each got.

#293 [FEAT/#274] 푸시 알림 관련 API 연결 및 모달 구현
  app/build.gradle.kts
  app/src/main/java/com/napzak/market/config/messaging/NapzakFirebaseMessaging.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakToggleButton.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/ContextExt.kt
  data/local/build.gradle.kts
  data/local/src/main/java/com/napzak/market/local/datastore/DataStoreModule.kt
  data/local/src/main/java/com/napzak/market/local/datastore/NotificationDataStore.kt
  data/local/src/main/java/com/napzak/market/local/datastore/TokenDataStore.kt
  data/notification/.gitignore
  data/notification/build.gradle.kts
  data/notification/consumer-rules.pro
  data/notification/proguard-rules.pro
  data/notification/src/main/AndroidManifest.xml
  data/notification/src/main/java/com/napzak/market/notification/datasource/NotificationDataSource.kt
  data/notification/src/main/java/com/napzak/market/notification/di/RepositoryModule.kt
  data/notification/src/main/java/com/napzak/market/notification/di/ServiceModule.kt
  data/notification/src/main/java/com/napzak/market/notification/dto/NotificationSettingsRequest.kt
  data/notification/src/main/java/com/napzak/market/notification/dto/NotificationSettingsResponse.kt
  data/notification/src/main/java/com/napzak/market/notification/dto/UpdatePushTokenRequest.kt
  data/notification/src/main/java/com/napzak/market/notification/mapper/NotificationMapper.kt
  data/notification/src/main/java/com/napzak/market/notification/repositoryimpl/NotificationRepositoryImpl.kt
  data/notification/src/main/java/com/napzak/market/notification/service/NotificationService.kt
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  domain/notification/.gitignore
  domain/notification/build.gradle.kts
  domain/notification/src/main/java/com/napzak/market/notification/model/EntireNotificationSettings.kt
  domain/notification/src/main/java/com/napzak/market/notification/model/NotificationSettings.kt
  domain/notification/src/main/java/com/napzak/market/notification/repository/NotificationRepository.kt
  domain/notification/src/main/java/com/napzak/market/notification/usecase/DeletePushTokenUseCase.kt
  domain/notification/src/main/java/com/napzak/market/notification/usecase/GetNotificationSettingsUseCase.kt
  domain/notification/src/main/java/com/napzak/market/notification/usecase/PatchNotificationSettingsUseCase.kt
  domain/notification/src/main/java/com/napzak/market/notification/usecase/UpdatePushTokenUseCase.kt
  feature/chat/build.gradle.kts
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/NotificationState.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/component/NotificationPermissionModal.kt
  feature/chat/src/main/java/com/napzak/market/chat/navigation/ChatNavigation.kt
  feature/chat/src/main/res/drawable/img_notification_permission.xml
  feature/chat/src/main/res/values/strings.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/HomeViewModel.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/component/SettingNotificationItem.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/withdraw/WithdrawViewModel.kt
  feature/mypage/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#302 [FIX/#301] 마켓 상세 페이지 디자인변경 사항 적용
  core/designsystem/src/main/res/drawable/ic_edit_pencil.xml
  core/designsystem/src/main/res/drawable/img_emtpy_upload.xml
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/BasicFilterChip.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/GenreChip.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreBottomSheetScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreEmptyView.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreInfoSection.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreReportBottomSheet.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreScrollSection.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreTopBar.kt
  feature/store/src/main/res/values/strings.xml
Labels: UI :iphone:, 충신채린 :saluting_face:

#305 [FIX/#300] 탐색화면 디자인 변경사항 반영
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/GenreFilterChip.kt
  core/designsystem/src/main/res/drawable/img_no_search_result.xml
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/res/values/string.xml
Labels: UI :iphone:, 충신채린 :saluting_face:

#304 [REFACTOR/#244] 등록화면 UX 보완
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakButton.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/ClearFocusOnScrollConnection.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/EmptyTextToolbar.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/ModifierExt.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationContract.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceSettingGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/component/PriceNegotiationGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ShippingFeeSelector.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ShippingFeeTextField.kt
Labels: REFACTOR :recycle:, 퍼시벌종명 :sunglasses:

#306 [REFACTOR/#299] 채팅방 수정
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatMessageResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomEnterResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomInformationResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomInformationMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatRoomRepositoryImpl.kt
  data/chat/src/test/resources/api-response/ChatRoomInformation.json
  domain/chat/src/main/java/com/napzak/market/chat/model/ProductBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ReceiveMessage.kt
  domain/chat/src/main/java/com/napzak/market/chat/repository/ChatRoomRepository.kt
  feature/chat/build.gradle.kts
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomUiState.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomInputField.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomItemColumn.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomProduct.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatItemContainers.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatProduct.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/preview/MockChats.kt
  feature/chat/src/main/res/values/strings.xml
Labels: REFACTOR :recycle:, 암살자석준 :rage:

#314 [FIX/#311] 마켓페이지 QA
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreEmptyView.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreInfoSection.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreScrollSection.kt
Labels: FIX :hammer:, UI :iphone:, 충신채린 :saluting_face:

#315 [FIX/#313] 찜 목록 화면 QA
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/WishlistScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/WishlistSideEffect.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/WishlistViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/component/WishlistTopSection.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/state/WishlistUiState.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/wishlist/.gitignore
  feature/wishlist/build.gradle.kts
  feature/wishlist/consumer-rules.pro
  feature/wishlist/proguard-rules.pro
  feature/wishlist/src/main/AndroidManifest.xml
  feature/wishlist/src/main/java/com/napzak/market/wishlist/navigation/WishlistNavigation.kt
  feature/wishlist/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: FIX :hammer:, UI :iphone:, 충신채린 :saluting_face:

#331 [REFACTOR/#330] 화면별 디자인 QA 사항 반영
  core/designsystem/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/WishlistScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/WishlistViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/wishlist/component/WishlistTopSection.kt
Labels: REFACTOR :recycle:, UI :iphone:, 충신채린 :saluting_face:

#322 [REFACTOR/#318] 2차 스프린트 QA 반영
  app/src/main/java/com/napzak/market/config/messaging/NapzakFirebaseMessaging.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/image/NapzakProfileImage.kt
  core/designsystem/src/main/res/drawable/ic_image_edit.xml
  core/designsystem/src/main/res/drawable/ic_profile.xml
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomInformationResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomInformationMapper.kt
  data/chat/src/test/resources/api-response/ChatRoomInformation.json
  domain/chat/src/main/java/com/napzak/market/chat/model/StoreBrief.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/component/ChatRoomItem.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomUiState.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomInputField.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomItemColumn.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomProduct.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/preview/MockChats.kt
  feature/chat/src/main/res/values/strings.xml
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductImageGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductMarketGroup.kt
  feature/detail/src/main/res/drawable/ic_profile.xml
  feature/detail/src/main/res/values/strings.xml
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalAutoScrollableImages.kt
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStoreNickNameSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStorePhotoSection.kt
  feature/store/src/main/res/drawable/ic_profile_basic.xml
  feature/store/src/main/res/values/strings.xml
Labels: REFACTOR :recycle:, 암살자석준 :rage:

#327 [FEAT/#324] 카카오 소셜로그인 릴리즈 SDK 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: FEAT :sparkles:, 멀린연진 :angel:

#335 [MOD/#334] 배송비 관련 문자열 수정
  feature/detail/src/main/res/values/strings.xml
Labels: MOD ✅, 퍼시벌종명 :sunglasses:

#338 [FIX/#336] 마켓 페이지 추가 QA
  core/common/src/main/java/com/napzak/market/common/type/MarketTab.kt
  core/designsystem/src/main/res/drawable/ic_cover_profile.xml
  feature/store/src/main/java/com/napzak/market/store/store/component/GenreChip.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreEmptyView.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreInfoSection.kt
  feature/store/src/main/java/com/napzak/market/store/store/component/StoreScrollSection.kt
Labels: FIX :hammer:, 충신채린 :saluting_face:

#344 [FIX/#337] 푸시 알림 관련 QA
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakToggleButton.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakToggleButtonDefault.kt
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/napzak/market/main/MainActivity.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/java/com/napzak/market/main/SessionManager.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/component/SettingNotificationItem.kt
Labels: FIX :hammer:, UI :iphone:, 충신채린 :saluting_face:

#343 [FIX/#342] 담당 화면 QA
  core/common/src/main/java/com/napzak/market/common/type/TradeStatusType.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/dialog/NapzakDialog.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/dialog/NapzakDialogDefault.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakLargeProductItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakSmallProductItem.kt
  core/designsystem/src/main/res/drawable/ic_purple_cart.xml
  core/designsystem/src/main/res/drawable/ic_purple_reservation.xml
  core/designsystem/src/main/res/drawable/ic_purple_sell_complete.xml
  core/designsystem/src/main/res/drawable/ic_red_heart_large.xml
  core/designsystem/src/main/res/drawable/ic_transparent_heart.xml
  core/designsystem/src/main/res/drawable/ic_transparent_heart_large.xml
  core/designsystem/src/main/res/drawable/img_product_complete_buy.png
  core/designsystem/src/main/res/drawable/img_product_complete_sell.png
  core/designsystem/src/main/res/drawable/img_product_reservation.png
  core/designsystem/src/main/res/drawable/img_thumbnail_complete_buy.png
  core/designsystem/src/main/res/drawable/img_thumbnail_complete_sell.png
  core/designsystem/src/main/res/drawable/img_thumbnail_reservation.png
  domain/store/src/main/java/com/napzak/market/store/model/NicknameValidationResult.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/ValidateNicknameUseCase.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomWithdrawDialog.kt
  feature/chat/src/main/res/values/strings.xml
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/bottombar/ProductDetailBottomBar.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/bottomsheet/MyProductBottomSheet.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductImageGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationBuyGroup.kt
  feature/detail/src/main/res/drawable/ic_back.xml
  feature/detail/src/main/res/drawable/ic_heart_filled_large.xml
  feature/detail/src/main/res/drawable/ic_heart_unfilled_large.xml
  feature/detail/src/main/res/drawable/ic_option.xml
  feature/detail/src/main/res/drawable/ic_product_buy_complete_large.xml
  feature/detail/src/main/res/drawable/ic_product_reservation_large.xml
  feature/detail/src/main/res/drawable/ic_product_sell_complete_large.xml
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameValidationResultExt.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameViewModel.kt
  feature/onboarding/src/main/res/values/strings.xml
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStoreNickNameSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStorePhotoSection.kt
  feature/store/src/main/res/drawable/ic_kebap.xml
  feature/store/src/main/res/drawable/ic_left_chevron.xml
  feature/store/src/main/res/drawable/ic_profile_edit.xml
  feature/store/src/main/res/drawable/ic_right_chevron.xml
  feature/store/src/main/res/values/strings.xml
Labels: FIX :hammer:, 암살자석준 :rage:

#340 [REFACTOR/#323] 채팅 관련 QA
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakThrottleButton.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/dialog/NapzakDialog.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/image/ZoomableImageScreen.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/SearchTextField.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_dark_gray_search.xml
  core/designsystem/src/main/res/drawable/ic_no_chatting_history.xml
  core/designsystem/src/main/res/drawable/ic_no_chatting_room.xml
  core/designsystem/src/main/res/drawable/img_chat_date_box.png
  core/designsystem/src/main/res/drawable/img_chat_divider.png
  core/ui_util/src/main/java/com/napzak/market/ui_util/ModifierExt.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatMessageMetadata.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRealtimeMessage.kt
  data/chat/src/main/java/com/napzak/market/chat/dto/ChatRoomInformationResponse.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRealtimeMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomInformationMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/mapper/ChatRoomMessageMapper.kt
  data/chat/src/main/java/com/napzak/market/chat/repositoryimpl/ChatSocketRepositoryImpl.kt
  data/chat/src/main/java/com/napzak/market/chat/service/ChatSocketService.kt
  data/chat/src/test/java/com/napzak/market/chat/ChatRoomInformationApiTest.kt
  data/chat/src/test/resources/api-response/ChatRoomInformation.json
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/remote/src/main/java/com/napzak/market/remote/StompSocketClient.kt
  data/remote/src/main/java/com/napzak/market/remote/qualifier/NetworkQualifier.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ChatRoom.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ProductBrief.kt
  domain/chat/src/main/java/com/napzak/market/chat/model/ReceiveMessage.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListUiState.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/ChatListViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/NotificationState.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatlist/component/ChatRoomItem.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomSideEffect.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/ChatRoomViewModel.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatImageZoomScreen.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomInputField.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomItemColumn.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ChatRoomProduct.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/ImageSendButton.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatDate.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatItemContainers.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatNotice.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/component/chatitem/ChatProduct.kt
  feature/chat/src/main/java/com/napzak/market/chat/chatroom/preview/MockChats.kt
  feature/chat/src/main/res/values/strings.xml
  feature/home/src/main/java/com/napzak/market/home/component/VerticalGridProducts.kt
  feature/main/src/main/java/com/napzak/market/main/WebSocketLifecycleObserver.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/component/MyPageMenuCard.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/type/MyPageMenu.kt
  feature/report/src/main/java/com/napzak/market/report/ReportScreen.kt
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
Labels: REFACTOR :recycle:, 암살자석준 :rage:
