Repository napzakmarket/Napzak-Android, pull requests merged in 2025-06, with the labels that each got.

#227 [REFACTOR/#222] 필터된 장르 리스트 말줄임표 적용 기준 변경
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/GenreFilterChip.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#232 [FEAT/#220] 커스텀 토스트 구현
  core/common/src/main/java/com/napzak/market/common/type/TradeStatusType.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/toast/CommonSnackBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/toast/HeartClickSnackBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/toast/NapzakToast.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/toast/NapzakToastType.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/toast/WarningSnackBar.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/SnackBarController.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailSideEffect.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/bottomsheet/MyProductBottomSheet.kt
  feature/detail/src/main/java/com/napzak/market/detail/type/ProductDetailToastType.kt
  feature/detail/src/main/res/values/strings.xml
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/java/com/napzak/market/main/component/MainSnackBarHost.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/report/src/main/java/com/napzak/market/report/ReportScreen.kt
  feature/report/src/main/java/com/napzak/market/report/ReportSideEffect.kt
  feature/report/src/main/java/com/napzak/market/report/ReportViewModel.kt
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#234 [FIX/#224] 탈퇴 및 로그아웃 데이터 스토어 토큰 삭제
  core/ui_util/src/main/java/com/napzak/market/ui_util/ContextExt.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/StringExt.kt
  core/util/build.gradle.kts
  core/util/src/main/java/com/napzak/market/util/android/StoreStateManager.kt
  core/util/src/main/java/com/napzak/market/util/android/TokenProvider.kt
  data/local/src/main/java/com/napzak/market/local/datastore/TokenDataStore.kt
  data/remote/build.gradle.kts
  data/remote/src/main/java/com/napzak/market/remote/AuthInterceptor.kt
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/store/build.gradle.kts
  data/store/src/main/java/com/napzak/market/store/di/AuthModule.kt
  data/store/src/main/java/com/napzak/market/store/di/RepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/WithdrawResponse.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/AuthRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreStateManagerImpl.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/TokenProviderImpl.kt
  domain/store/build.gradle.kts
  domain/store/src/main/java/com/napzak/market/store/model/UserWithdrawal.kt
  domain/store/src/main/java/com/napzak/market/store/repository/TokenProvider.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/CheckAutoLoginUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/LogoutUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/WithdrawUseCase.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/GenreNavigationButton.kt
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalScrollableProducts.kt
  feature/home/src/main/java/com/napzak/market/home/component/VerticalGridProducts.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/withdraw/WithdrawViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreItem.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/GenreSearchScreen.kt
  feature/search/src/main/java/com/napzak/market/search/component/GenreNavigationButtton.kt
  feature/store/src/main/java/com/napzak/market/store/component/GenreChip.kt
Labels: FIX :hammer:, 멀린연진 :angel:

#235 [REFACTOR/#233] 홈 QA 사항 반영
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakLargeProductItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakSmallProductItem.kt
  core/ui_util/src/main/java/com/napzak/market/ui_util/FlowExt.kt
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/HomeSideEffect.kt
  feature/home/src/main/java/com/napzak/market/home/HomeViewModel.kt
  feature/home/src/main/java/com/napzak/market/home/state/HomeUiState.kt
  feature/home/src/main/java/com/napzak/market/home/type/HomeProductType.kt
  feature/home/src/main/res/values/strings.xml
Labels: REFACTOR :recycle:, 암살자석준 :rage:

#239 [Fix/#216] 검색장르가 기본 추천 장르에 추가되는 현상 해결
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
Labels: FIX :hammer:, 멀린연진 :angel:

#242 [REFACTOR/#238] 마켓 페이지 QA
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreSideEffect.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreViewModel.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#237 [REFACTOR/#236] 탐색 탭 QA 반영
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreSideEffect.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreViewModel.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#226 [FIX/#215] 등록 화면 추가 QA 반영
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationContract.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceIncrementer.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationTopBar.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/GenreSearchScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/GenreSearchViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/state/GenreContract.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
  feature/registration/src/main/res/values/string.xml
Labels: FIX :hammer:, 퍼시벌종명 :sunglasses:

#249 [DELETE/#248] Dummy 모듈 삭제
  app/build.gradle.kts
  data/dummy/.gitignore
  data/dummy/build.gradle.kts
  data/dummy/consumer-rules.pro
  data/dummy/proguard-rules.pro
  data/dummy/src/main/AndroidManifest.xml
  data/dummy/src/main/java/com/napzak/market/dummy/datasource/DummyDataSource.kt
  data/dummy/src/main/java/com/napzak/market/dummy/di/DummyRepositoryModule.kt
  data/dummy/src/main/java/com/napzak/market/dummy/di/DummyServiceModule.kt
  data/dummy/src/main/java/com/napzak/market/dummy/dto/GetUserListResponse.kt
  data/dummy/src/main/java/com/napzak/market/dummy/mapper/toDummyUser.kt
  data/dummy/src/main/java/com/napzak/market/dummy/repositoryimpl/DummyRepositoryImpl.kt
  data/dummy/src/main/java/com/napzak/market/dummy/service/DummyService.kt
  data/dummy/src/test/java/com/napzak/market/dummy/ExampleUnitTest.kt
  data/remote/build.gradle.kts
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/remote/src/main/java/com/napzak/market/remote/qualifier/NetworkQualifier.kt
  domain/dummy/.gitignore
  domain/dummy/build.gradle.kts
  domain/dummy/src/main/java/com/napzak/market/dummy/model/DummyUser.kt
  domain/dummy/src/main/java/com/napzak/market/dummy/repository/DummyRepository.kt
  feature/dummy/.gitignore
  feature/dummy/build.gradle.kts
  feature/dummy/consumer-rules.pro
  feature/dummy/proguard-rules.pro
  feature/dummy/src/main/AndroidManifest.xml
  feature/dummy/src/main/java/com/napzak/market/dummy/DummyScreen.kt
  feature/dummy/src/main/java/com/napzak/market/dummy/DummyViewModel.kt
  feature/dummy/src/main/java/com/napzak/market/dummy/component/DummyUserItem.kt
  feature/dummy/src/main/java/com/napzak/market/dummy/navigation/DummyNavigation.kt
  feature/dummy/src/main/java/com/napzak/market/dummy/state/DummyState.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainTab.kt
  settings.gradle.kts
Labels: DELETE :wastebasket:, 암살자석준 :rage:

#250 [UI/#246] 찜 목록 UI 구현
  core/designsystem/src/main/res/drawable/ic_left_chevron.xml
  core/designsystem/src/main/res/drawable/img_empty_wishlist.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/wishlist/.gitignore
  feature/wishlist/build.gradle.kts
  feature/wishlist/consumer-rules.pro
  feature/wishlist/proguard-rules.pro
  feature/wishlist/src/main/AndroidManifest.xml
  feature/wishlist/src/main/java/com/napzak/market/wishlist/WishlistScreen.kt
  feature/wishlist/src/main/java/com/napzak/market/wishlist/WishlistSideEffect.kt
  feature/wishlist/src/main/java/com/napzak/market/wishlist/WishlistViewModel.kt
  feature/wishlist/src/main/java/com/napzak/market/wishlist/component/WishlistTopSection.kt
  feature/wishlist/src/main/java/com/napzak/market/wishlist/navigation/WishlistNavigation.kt
  feature/wishlist/src/main/java/com/napzak/market/wishlist/state/WishlistUiState.kt
  feature/wishlist/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: UI :iphone:, 충신채린 :saluting_face:
