Repository napzakmarket/Napzak-Android, pull requests merged in 2025-04, with the labels that each got.

#26 [UI/#8] 공통 컴포넌트 구현 (bottomsheet)
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/BottomSheetMenuItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/DragHandleBottomSheet.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/Genre.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/SortBottomSheet.kt
  core/designsystem/src/main/res/drawable/ic_check_purple.xml
  core/designsystem/src/main/res/drawable/ic_delete_24.xml
  core/designsystem/src/main/res/drawable/ic_down_chevron.xml
  core/designsystem/src/main/res/drawable/ic_edit_24.xml
  core/designsystem/src/main/res/drawable/ic_error_24.xml
  core/designsystem/src/main/res/drawable/ic_selected_dot_14.xml
  core/designsystem/src/main/res/drawable/ic_setting_24.xml
  core/designsystem/src/main/res/drawable/ic_unselected_dot_14.xml
  core/designsystem/src/main/res/drawable/ic_up_chevron.xml
  core/designsystem/src/main/res/drawable/ic_x_button_24.xml
  core/designsystem/src/main/res/values/strings.xml
Labels: UI :iphone:, 충신채린 :saluting_face:

#28 [UI/#27] 공통 컴포넌트 구현 (tab bar)
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/tabbar/MarketTabBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/tabbar/TabBarItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/tabbar/TradeTypeTabBar.kt
Labels: UI :iphone:, 충신채린 :saluting_face:

#38 [CHORE/#37] 텍스트 필드 수정
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/NapzakDefaultTextField.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/SearchTextField.kt
Labels: CHORE :chains:, 퍼시벌종명 :sunglasses:

#49 [CHORE#47] 텍스트 초기화 아이콘 등장 로직 변경
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/SearchTextField.kt
Labels: CHORE :chains:, 퍼시벌종명 :sunglasses:

#48 [UI/#46] 다이얼로그 컴포넌트 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/dialog/NapzakDialog.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/dialog/NapzakDialogDefault.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: UI :iphone:, 암살자석준 :rage:

#53 [UI/#23] 바텀바 컴포넌트
  core/designsystem/src/main/res/drawable/ic_nav_add.xml
  core/designsystem/src/main/res/drawable/ic_nav_chat.xml
  core/designsystem/src/main/res/drawable/ic_nav_explore.xml
  core/designsystem/src/main/res/drawable/ic_nav_home.xml
  core/designsystem/src/main/res/drawable/ic_nav_user.xml
  core/designsystem/src/main/res/drawable/ic_register_buy.xml
  core/designsystem/src/main/res/drawable/ic_register_sell.xml
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/java/com/napzak/market/main/MainTab.kt
  feature/main/src/main/java/com/napzak/market/main/component/MainBottomBar.kt
  feature/main/src/main/java/com/napzak/market/main/component/MainRegisterDialog.kt
  feature/main/src/main/res/values/strings.xml
Labels: UI :iphone:, 암살자석준 :rage:

#44 [UI/#15] 상세페이지 화면 구현
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailSideEffect.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationBuyGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationSellGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductMarketGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/ProductDetail.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/ProductPhoto.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/StoreInfo.kt
  feature/detail/src/main/java/com/napzak/market/detail/navigation/ProductDetailNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
Labels: UI :iphone:, 암살자석준 :rage:

#54 [UI/#10] 팔아요/구해요 등록 화면 및 컴포넌트 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/InputTextField.kt
  core/designsystem/src/main/res/drawable/ic_arrow_right_gray.xml
  core/designsystem/src/main/res/drawable/ic_error_9.xml
  core/util/src/main/java/com/napzak/market/util/android/NumericVisualTransformation.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceIncrementer.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceSettingGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationGenreButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/component/PriceNegotiationGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ProductConditionGridButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ShippingFeeSelector.kt
  feature/registration/src/main/res/values/string.xml
Labels: UI :iphone:, 퍼시벌종명 :sunglasses:

#50 [UI/#10] Registration Components
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/InputTextField.kt
  core/designsystem/src/main/res/drawable/ic_cancel_image_24.xml
  core/designsystem/src/main/res/drawable/ic_close_24.xml
  core/designsystem/src/main/res/drawable/ic_error_9.xml
  core/designsystem/src/main/res/drawable/ic_import_24.xml
  core/util/src/main/java/com/napzak/market/util/android/NumericVisualTransformation.kt
  feature/registration/.gitignore
  feature/registration/build.gradle.kts
  feature/registration/consumer-rules.pro
  feature/registration/src/main/AndroidManifest.xml
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoPicker.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceIncrementer.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PriceSettingGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationGenreButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationTopBar.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/SectionDivider.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/component/PriceNegotiationGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ProductConditionGridButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ShippingFeeSelector.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/component/ShippingFeeTextField.kt
  feature/registration/src/main/res/values/string.xml
  settings.gradle.kts
Labels: UI :iphone:, 퍼시벌종명 :sunglasses:

#56 [UI/#41] 장르상세페이지 구현
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/napzak/market/explore/component/GenreLabel.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/GenreNavigationButton.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/res/drawable/ic_home.xml
  feature/explore/src/main/res/drawable/ic_left_chevron_24.xml
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
Labels: UI :iphone:, 충신채린 :saluting_face:

#63 [CHORE/#62] 장르 바텀시트 수정
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: CHORE :chains:, 충신채린 :saluting_face:

#25 [UI/#24] 마이페이지 뷰 구현
  core/designsystem/src/main/res/drawable/ic_arrow_right_7.xml
  core/designsystem/src/main/res/drawable/ic_favorite_27.xml
  core/designsystem/src/main/res/drawable/ic_help_32.xml
  core/designsystem/src/main/res/drawable/ic_profile_60.xml
  core/designsystem/src/main/res/drawable/ic_purchase_32.xml
  core/designsystem/src/main/res/drawable/ic_recent_30.xml
  core/designsystem/src/main/res/drawable/ic_sales_32.xml
  core/designsystem/src/main/res/drawable/ic_settings_27.xml
  feature/mypage/.gitignore
  feature/mypage/build.gradle.kts
  feature/mypage/consumer-rules.pro
  feature/mypage/src/main/AndroidManifest.xml
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageMenu.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/component/MyMarketButton.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/component/MyPageMenuCard.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/component/MyPageProfileSection.kt
  feature/mypage/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: UI :iphone:, 모드레드재원 :imp:

#60 [UI/#32] 이용약관 온보딩 UI 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/button/NapzakCheckedButton.kt
  core/designsystem/src/main/res/drawable/ic_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_arrow_right.xml
  core/designsystem/src/main/res/drawable/ic_first_step_indicator.xml
  core/util/src/main/java/com/napzak/market/util/android/ModifierExt.kt
  core/util/src/main/java/com/napzak/market/util/common/ContextExt.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/proguard-rules.pro
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/model/TermType.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/model/TermsAgreementUiState.kt
  feature/onboarding/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT :sparkles:, 멀린연진 :angel:

#59 [UI/#17] 프로필 수정 뷰 구현
  feature/detail/src/main/java/com/napzak/market/detail/navigation/ProductDetailNavigation.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/navigation/EditStoreNavigation.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/navigation/StoreNavigation.kt
  feature/store/src/main/res/drawable/ic_profile_basic.xml
  feature/store/src/main/res/drawable/ic_profile_edit.xml
  feature/store/src/main/res/values/strings.xml
Labels: UI :iphone:, 암살자석준 :rage:

#71 [FEAT/#58] 구해요 등록화면 로직 구현
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoContainer.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoPicker.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationGenreButton.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/state/PurchaseContract.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#72 [UI/#33] 온보딩 닉네임 뷰 구현
  core/designsystem/src/main/res/drawable/ic_second_step_indicator.xml
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameErrorType.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameUiState.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameValidationResult.kt
  feature/onboarding/src/main/res/values/strings.xml
Labels: UI :iphone:, 멀린연진 :angel:

#68 [UI/#30] 설정페이지 구현
  core/designsystem/src/main/res/drawable/ic_arrow_left_9.xml
  core/designsystem/src/main/res/drawable/ic_arrow_right_9.xml
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsMenu.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/component/SettingItem.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/component/SettingsTopBar.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: UI :iphone:, 모드레드재원 :imp:

#61 [FEAT/#57] 탐색 탭 기능 구현
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/ExploreBottomSheetScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/navigation/ExploreNavigation.kt
  feature/explore/src/main/java/com/napzak/market/explore/state/ExploreBottomSheetState.kt
  feature/explore/src/main/java/com/napzak/market/explore/state/ExploreUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:
