Repository napzakmarket/Napzak-Android, pull requests merged in 2025-05, with the labels that each got.

#81 [FEAT/#80] 상세관련 Product API 연결
  data/product/src/main/java/com/napzak/market/product/datasource/ProductDetailDataSource.kt
  data/product/src/main/java/com/napzak/market/product/di/RepositoryModule.kt
  data/product/src/main/java/com/napzak/market/product/di/ServiceModule.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductGetDetailResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductPatchTradeStatusRequest.kt
  data/product/src/main/java/com/napzak/market/product/mapper/ProductDetailMapper.kt
  data/product/src/main/java/com/napzak/market/product/repositoryimpl/ProductDetailRepositoryImpl.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductDetailService.kt
  domain/product/src/main/java/com/napzak/market/product/model/ProductDetail.kt
  domain/product/src/main/java/com/napzak/market/product/repository/ProductDetailRepository.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#107 [FEAT/#73] Presigned Url API 연결
  app/build.gradle.kts
  data/presigned-url/.gitignore
  data/presigned-url/build.gradle.kts
  data/presigned-url/consumer-rules.pro
  data/presigned-url/proguard-rules.pro
  data/presigned-url/src/main/AndroidManifest.xml
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/datasource/PresignedUrlDataSource.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/di/RepositoryModule.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/di/ServiceModule.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/dto/ProductPresignedUrlResponse.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/dto/ProfilePresignedUrlResponse.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/mapper/PresignedUrlMapper.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepositoryImpl.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/service/PresignedUrlService.kt
  domain/presigned-url/.gitignore
  domain/presigned-url/build.gradle.kts
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/model/PresignedUrl.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#108 [FEAT/#70] 등록 API 연결
  data/registration/.gitignore
  data/registration/build.gradle.kts
  data/registration/consumer-rules.pro
  data/registration/proguard-rules.pro
  data/registration/src/main/AndroidManifest.xml
  data/registration/src/main/java/com/napzak/market/registration/datasource/RegistrationDataSource.kt
  data/registration/src/main/java/com/napzak/market/registration/di/RepositoryModule.kt
  data/registration/src/main/java/com/napzak/market/registration/di/ServiceModule.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/ProductIdDto.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/ProductPhotoDto.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/PurchaseRegistrationRequest.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/PurchaseRegistrationResponse.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/SaleRegistrationRequest.kt
  data/registration/src/main/java/com/napzak/market/registration/dto/SaleRegistrationResponse.kt
  data/registration/src/main/java/com/napzak/market/registration/mapper/RegistrationProductMapper.kt
  data/registration/src/main/java/com/napzak/market/registration/repository/RegistrationRepositoryImpl.kt
  data/registration/src/main/java/com/napzak/market/registration/service/RegistrationService.kt
  domain/registration/.gitignore
  domain/registration/build.gradle.kts
  domain/registration/src/main/java/com/napzak/market/registration/model/Product.kt
  domain/registration/src/main/java/com/napzak/market/registration/repository/RegistrationRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#97 [FEAT/#94] 장르 관련 API 구현
  app/build.gradle.kts
  data/genre/.gitignore
  data/genre/build.gradle.kts
  data/genre/consumer-rules.pro
  data/genre/proguard-rules.pro
  data/genre/src/main/AndroidManifest.xml
  data/genre/src/main/java/com/napzak/market/genre/datasource/GenreInfoDataSource.kt
  data/genre/src/main/java/com/napzak/market/genre/datasource/GenreNameDataSource.kt
  data/genre/src/main/java/com/napzak/market/genre/datasource/PreferredGenreDataSource.kt
  data/genre/src/main/java/com/napzak/market/genre/datasource/SearchWordGenreDataSource.kt
  data/genre/src/main/java/com/napzak/market/genre/di/RepositoryModule.kt
  data/genre/src/main/java/com/napzak/market/genre/di/ServiceModule.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/GenreInfoResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/GenreItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/GenreResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/GenreSearchItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/PreferredGenreItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/PreferredGenreSearchItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/RecommendedSearchWordGenreResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/GenreInfoMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/GenreItemsMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/GenreSearchItemsMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/PreferredGenreItemsMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/PreferredGenreSearchItemsMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/SearchWordGenreMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/repositoryimpl/GenreInfoRepositoryImpl.kt
  data/genre/src/main/java/com/napzak/market/genre/repositoryimpl/GenreNameRepositoryImpl.kt
  data/genre/src/main/java/com/napzak/market/genre/repositoryimpl/PreferredGenreRepositoryImpl.kt
  data/genre/src/main/java/com/napzak/market/genre/repositoryimpl/SearchWordGenreRepositoryImpl.kt
  data/genre/src/main/java/com/napzak/market/genre/service/GenreInfoService.kt
  data/genre/src/main/java/com/napzak/market/genre/service/GenreNameService.kt
  data/genre/src/main/java/com/napzak/market/genre/service/PreferredGenreService.kt
  data/genre/src/main/java/com/napzak/market/genre/service/SearchWordGenreService.kt
  domain/genre/.gitignore
  domain/genre/build.gradle.kts
  domain/genre/src/main/java/com/napzak/market/genre/model/Genre.kt
  domain/genre/src/main/java/com/napzak/market/genre/model/GenreInfo.kt
  domain/genre/src/main/java/com/napzak/market/genre/model/GenreSearchItems.kt
  domain/genre/src/main/java/com/napzak/market/genre/model/PreferredGenreSearchItems.kt
  domain/genre/src/main/java/com/napzak/market/genre/model/RecommendedSearchWordGenre.kt
  domain/genre/src/main/java/com/napzak/market/genre/repository/GenreInfoRepository.kt
  domain/genre/src/main/java/com/napzak/market/genre/repository/GenreNameRepository.kt
  domain/genre/src/main/java/com/napzak/market/genre/repository/PreferredGenreRepository.kt
  domain/genre/src/main/java/com/napzak/market/genre/repository/SearchWordGenreRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#111 [FEAT/#90] 마이(+설정)페이지 API 연결
  data/store/.gitignore
  data/store/build.gradle.kts
  data/store/consumer-rules.pro
  data/store/src/main/AndroidManifest.xml
  data/store/src/main/java/com/napzak/market/store/datasource/SettingDataSource.kt
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/di/StoreRepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/di/StoreServiceModule.kt
  data/store/src/main/java/com/napzak/market/store/dto/SettingInfoResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/StoreDetailResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/StoreEditProfileRequest.kt
  data/store/src/main/java/com/napzak/market/store/dto/StoreEditProfileResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/StoreResponse.kt
  data/store/src/main/java/com/napzak/market/store/mapper/SettingInfoMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreDetailMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreEditProfileMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreMapper.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/SettingRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/service/SettingService.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
  domain/store/.gitignore
  domain/store/build.gradle.kts
  domain/store/consumer-rules.pro
  domain/store/src/main/AndroidManifest.xml
  domain/store/src/main/java/com/napzak/market/store/model/SettingInfo.kt
  domain/store/src/main/java/com/napzak/market/store/model/StoreDetail.kt
  domain/store/src/main/java/com/napzak/market/store/model/StoreEditProfile.kt
  domain/store/src/main/java/com/napzak/market/store/model/StoreInfo.kt
  domain/store/src/main/java/com/napzak/market/store/repository/SettingRepository.kt
  domain/store/src/main/java/com/napzak/market/store/repository/StoreRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#110 [FEAT/#101] Interest 도메인 API 연결
  app/build.gradle.kts
  data/interest/.gitignore
  data/interest/build.gradle.kts
  data/interest/consumer-rules.pro
  data/interest/proguard-rules.pro
  data/interest/src/main/AndroidManifest.xml
  data/interest/src/main/java/com/napzak/market/interest/datasource/InterestProductDataSource.kt
  data/interest/src/main/java/com/napzak/market/interest/di/RepositoryModule.kt
  data/interest/src/main/java/com/napzak/market/interest/di/ServiceModule.kt
  data/interest/src/main/java/com/napzak/market/interest/repositoryimpl/InterestProductRepositoryImpl.kt
  data/interest/src/main/java/com/napzak/market/interest/service/InterestProductService.kt
  domain/interest/.gitignore
  domain/interest/build.gradle.kts
  domain/interest/src/main/java/com/napzak/market/interest/repository/InterestProductRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 암살자석준 :rage:

#100 [FEAT/#85] Banner API 연결
  app/build.gradle.kts
  data/banner/.gitignore
  data/banner/build.gradle.kts
  data/banner/consumer-rules.pro
  data/banner/proguard-rules.pro
  data/banner/src/main/AndroidManifest.xml
  data/banner/src/main/java/com/napzak/market/banner/BannerMapper.kt
  data/banner/src/main/java/com/napzak/market/banner/datasource/BannerDataSource.kt
  data/banner/src/main/java/com/napzak/market/banner/di/RepositoryModule.kt
  data/banner/src/main/java/com/napzak/market/banner/di/ServiceModule.kt
  data/banner/src/main/java/com/napzak/market/banner/dto/BannerResponse.kt
  data/banner/src/main/java/com/napzak/market/banner/dto/HomeBannerResponse.kt
  data/banner/src/main/java/com/napzak/market/banner/repositoryimpl/BannerRepositoryImpl.kt
  data/banner/src/main/java/com/napzak/market/banner/service/BannerService.kt
  domain/banner/.gitignore
  domain/banner/build.gradle.kts
  domain/banner/src/main/java/com/napzak/market/banner/Banner.kt
  domain/banner/src/main/java/com/napzak/market/repository/BannerRepository.kt
  domain/banner/src/main/java/com/napzak/market/type/HomeBannerType.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 암살자석준 :rage:

#96 [FEAT/#84] Report API 연결
  app/build.gradle.kts
  data/report/.gitignore
  data/report/build.gradle.kts
  data/report/consumer-rules.pro
  data/report/proguard-rules.pro
  data/report/src/main/AndroidManifest.xml
  data/report/src/main/java/com/napzak/market/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/napzak/market/report/di/ReportRepositoryModule.kt
  data/report/src/main/java/com/napzak/market/report/di/ServiceModule.kt
  data/report/src/main/java/com/napzak/market/report/dto/ReportProductResponse.kt
  data/report/src/main/java/com/napzak/market/report/dto/ReportRequest.kt
  data/report/src/main/java/com/napzak/market/report/dto/ReportStoreResponse.kt
  data/report/src/main/java/com/napzak/market/report/mapper/ReportMapper.kt
  data/report/src/main/java/com/napzak/market/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/napzak/market/report/service/ReportService.kt
  domain/report/.gitignore
  domain/report/build.gradle.kts
  domain/report/src/main/java/com/napzak/market/report/model/ReportParameters.kt
  domain/report/src/main/java/com/napzak/market/report/repository/ReportRepository.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 암살자석준 :rage:

#77 [FEAT/#74] 홈관련 Product API 연결
  app/build.gradle.kts
  data/product/.gitignore
  data/product/build.gradle.kts
  data/product/consumer-rules.pro
  data/product/proguard-rules.pro
  data/product/src/main/AndroidManifest.xml
  data/product/src/main/java/com/napzak/market/product/datasource/ProductDetailDataSource.kt
  data/product/src/main/java/com/napzak/market/product/datasource/ProductExploreDataSource.kt
  data/product/src/main/java/com/napzak/market/product/datasource/ProductRecommendationDataSource.kt
  data/product/src/main/java/com/napzak/market/product/datasource/ProductStoreDataSource.kt
  data/product/src/main/java/com/napzak/market/product/di/RepositoryModule.kt
  data/product/src/main/java/com/napzak/market/product/di/ServiceModule.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductExploreBuyResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductExploreSellResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductGetDetailResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductHomeBuyResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductHomeRecommendResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductHomeSellResponse.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductPatchTradeStatusRequest.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductResponse.kt
  data/product/src/main/java/com/napzak/market/product/mapper/ProductDetailMapper.kt
  data/product/src/main/java/com/napzak/market/product/mapper/ProductRecommendationMapper.kt
  data/product/src/main/java/com/napzak/market/product/repositoryimpl/ProductDetailRepositoryImpl.kt
  data/product/src/main/java/com/napzak/market/product/repositoryimpl/ProductExploreRepositoryImpl.kt
  data/product/src/main/java/com/napzak/market/product/repositoryimpl/ProductRecommendationRepositoryImpl.kt
  data/product/src/main/java/com/napzak/market/product/repositoryimpl/ProductStoreRepositoryImpl.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductDetailService.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductExploreService.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductRecommendationService.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductStoreService.kt
  data/remote/build.gradle.kts
  data/remote/src/main/java/com/napzak/market/remote/HeaderInterceptor.kt
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  domain/product/.gitignore
  domain/product/build.gradle.kts
  domain/product/src/main/java/com/napzak/market/product/model/ExploreParameters.kt
  domain/product/src/main/java/com/napzak/market/product/model/Product.kt
  domain/product/src/main/java/com/napzak/market/product/model/ProductDetail.kt
  domain/product/src/main/java/com/napzak/market/product/model/SearchParameters.kt
  domain/product/src/main/java/com/napzak/market/product/repository/ProductDetailRepository.kt
  domain/product/src/main/java/com/napzak/market/product/repository/ProductExploreRepository.kt
  domain/product/src/main/java/com/napzak/market/product/repository/ProductRecommendationRepository.kt
  domain/product/src/main/java/com/napzak/market/product/repository/ProductStoreRepository.kt
  domain/store/src/main/java/com/napzak/market/store/model/StoreDetail.kt
  feature/store/build.gradle.kts
  feature/store/src/main/java/com/napzak/market/store/model/StoreInfo.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 암살자석준 :rage:

#109 [Feat/#104] store api 연결
  app/build.gradle.kts
  core/designsystem/src/main/res/drawable/ic_delete_circle_button.xml
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_reset.xml
  core/designsystem/src/main/res/drawable/img_sample.png
  core/util/src/main/java/com/napzak/market/util/common/StringExt.kt
  data/store/build.gradle.kts
  data/store/proguard-rules.pro
  data/store/src/main/java/com/napzak/market/store/datasource/SettingDataSource.kt
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/di/RepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/di/ServiceModule.kt
  data/store/src/main/java/com/napzak/market/store/dto/request/GenreRegistrationRequest.kt
  data/store/src/main/java/com/napzak/market/store/dto/request/NicknameRequest.kt
  data/store/src/main/java/com/napzak/market/store/dto/request/StoreEditProfileRequest.kt
  data/store/src/main/java/com/napzak/market/store/dto/request/WithdrawRequest.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/GenreRegistrationResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/SettingInfoResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreDetailResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreEditProfileResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/WithdrawResponse.kt
  data/store/src/main/java/com/napzak/market/store/mapper/SettingInfoMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreDetailMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreEditProfileMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreMapper.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/service/SettingService.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
  domain/store/build.gradle.kts
  domain/store/proguard-rules.pro
  domain/store/src/main/java/com/napzak/market/store/model/Genre.kt
  domain/store/src/main/java/com/napzak/market/store/model/UserWithdrawal.kt
  domain/store/src/main/java/com/napzak/market/store/repository/StoreRepository.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreItem.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreUiModel.kt
  settings.gradle.kts
Labels: FEAT :sparkles:, 멀린연진 :angel:

#114 [FEAT/#113] 좋아요 UseCase 구현
  domain/interest/build.gradle.kts
  domain/interest/src/main/java/com/napzak/market/interest/usecase/InterestProductUseCase.kt
  gradle/libs.versions.toml
Labels: FEAT :sparkles:, 암살자석준 :rage:

#116 [ADD/#115] data를 포함하지 않는 응답 모델 추가
  data/interest/src/main/java/com/napzak/market/interest/service/InterestProductService.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductDetailService.kt
  data/remote/src/main/java/com/napzak/market/remote/model/EmptyDataResponse.kt
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
Labels: ADD ➕, FIX :hammer:, 암살자석준 :rage:

#106 [MOD/#103] genre navigate button UI 수정
  feature/search/src/main/java/com/napzak/market/search/component/GenreNavigationButtton.kt
Labels: MOD ✅, 충신채린 :saluting_face:

#125 [HOTFIX/#124] genreList의 Item core로 컴포넌트 분리
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/GenreListItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
Labels: HOTFIX :hammer_and_wrench:, 충신채린 :saluting_face:

#138 [FIX/#132] 스낵바 영역 수정
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/WarningSnackBar.kt
Labels: FIX :hammer:, 모드레드재원 :imp:

#129 [FIX/#99] bottom sheet 오류 해결
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/SortBottomSheet.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/ExploreBottomSheetScreen.kt
Labels: FIX :hammer:, 충신채린 :saluting_face:

#133 [UI/#34] 장르 선택 온보딩 뷰 구현
  core/designsystem/src/main/res/drawable/ic_third_step_indicator.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreUiState.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/navigation/OnboardingNavigator.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
  feature/onboarding/src/main/res/values/strings.xml
Labels: UI :iphone:, 멀린연진 :angel:

#142 [Add/#141] ContentResolverModule 추가
  data/remote/src/main/java/com/napzak/market/remote/ContentResolverModule.kt
Labels: ADD ➕, 퍼시벌종명 :sunglasses:

#140 [Feat/#135] 닉네임 등록 기능 구현
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/di/RepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/di/ServiceModule.kt
  data/store/src/main/java/com/napzak/market/store/di/StoreRepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/di/StoreServiceModule.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
  domain/store/build.gradle.kts
  domain/store/src/main/java/com/napzak/market/store/usecase/CheckNicknameDuplicationUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/SetNicknameUseCase.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameUiState.kt
Labels: FEAT :sparkles:, 멀린연진 :angel:

#98 [FEAT/#87] Genre상세 페이지 기능 구현
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/state/GenreDetailUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#102 [FEAT/#88] 검색화면 기능 구현
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
  feature/search/src/main/java/com/napzak/market/search/SearchViewModel.kt
  feature/search/src/main/java/com/napzak/market/search/state/SearchUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#151 Fix/#150 retrofit s3
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/di/ServiceModule.kt
  data/remote/src/main/java/com/napzak/market/remote/NetworkModule.kt
  data/remote/src/main/java/com/napzak/market/remote/qualifier/NetworkQualifier.kt
Labels: FIX :hammer:, 암살자석준 :rage:

#149 [FEAT]/#148 Presigned Url API usecase 생성 및 model 수정
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/mapper/PresignedUrlMapper.kt
  data/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepositoryImpl.kt
  domain/presigned-url/build.gradle.kts
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/model/PresignedUrl.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/repository/PresignedUrlRepository.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/GetProductPresignedUrlUseCase.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/UploadImageUseCase.kt
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#128 [FEAT/#126] 마이페이지 기능구현
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreResponse.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreMapper.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/java/com/napzak/market/main/MainTab.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/model/MyPageViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/state/MyPageUiState.kt
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#67 [UI/#66] 탈퇴화면 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/spinner/NapzakSpinner.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/topbar/NavigateUpTopBar.kt
  core/designsystem/src/main/res/values/strings.xml
  core/util/build.gradle.kts
  core/util/src/main/java/com/napzak/market/util/android/NavBackStackEntryExt.kt
  core/util/src/main/java/com/napzak/market/util/android/NavGraphBuilderExt.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutConfirmScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutDetailScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutReasonScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/navigation/SignOutNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/type/SignOutReasonType.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: UI :iphone:, 암살자석준 :rage:

#117 [FEAT/#112] 홈화면 기능 구현
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/napzak/market/home/HomeScreen.kt
  feature/home/src/main/java/com/napzak/market/home/HomeViewModel.kt
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalAutoScrollableImages.kt
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalScrollableProducts.kt
  feature/home/src/main/java/com/napzak/market/home/component/VerticalGridProducts.kt
  feature/home/src/main/java/com/napzak/market/home/model/Product.kt
  feature/home/src/main/java/com/napzak/market/home/state/HomeUiState.kt
  feature/main/src/main/java/com/napzak/market/main/component/MainBottomBar.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#122 [FEAT/#119] 신고화면 기능 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/CommonSnackBar.kt
  core/util/src/main/java/com/napzak/market/util/android/SnackBarController.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/report/build.gradle.kts
  feature/report/src/main/java/com/napzak/market/report/ReportScreen.kt
  feature/report/src/main/java/com/napzak/market/report/ReportSideEffect.kt
  feature/report/src/main/java/com/napzak/market/report/ReportViewModel.kt
  feature/report/src/main/java/com/napzak/market/report/component/ReportContactSection.kt
  feature/report/src/main/java/com/napzak/market/report/component/ReportDetailSection.kt
  feature/report/src/main/java/com/napzak/market/report/component/ReportReasonSection.kt
  feature/report/src/main/java/com/napzak/market/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 암살자석준 :rage:

#152 [FEAT/#130] 물품 등록 API 연동
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/PutViaPresignedUrlUseCase.kt
  domain/registration/build.gradle.kts
  domain/registration/src/main/java/com/napzak/market/registration/model/Product.kt
  domain/registration/src/main/java/com/napzak/market/registration/usecase/RegisterProductUseCase.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationContract.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoPicker.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/model/Photo.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#147 [Feat/#136] 장르 온보딩 기능 구현
  data/genre/src/main/java/com/napzak/market/genre/datasource/PreferredGenreDataSource.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/PreferredGenreItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/dto/PreferredGenreSearchItemsResponse.kt
  data/genre/src/main/java/com/napzak/market/genre/mapper/PreferredGenreItemsMapper.kt
  data/genre/src/main/java/com/napzak/market/genre/repositoryimpl/PreferredGenreRepositoryImpl.kt
  data/genre/src/main/java/com/napzak/market/genre/service/PreferredGenreService.kt
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
  domain/genre/build.gradle.kts
  domain/genre/src/main/java/com/napzak/market/genre/model/PreferredGenreSearchItems.kt
  domain/genre/src/main/java/com/napzak/market/genre/repository/PreferredGenreRepository.kt
  domain/genre/src/main/java/com/napzak/market/genre/usecase/SetPreferredGenreUseCase.kt
  domain/genre/src/main/java/com/napzak/market/genre/usecase/SetSearchPreferredGenreUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/SetRegisterGenres.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreMapeer.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreUiModel.kt
Labels: FEAT :sparkles:, 멀린연진 :angel:

#155 [FEAT/#143] 탐색탭 API 연결
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
  domain/genre/src/main/java/com/napzak/market/genre/model/Genre.kt
  feature/explore/build.gradle.kts
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/ExploreBottomSheetScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/GenreFilterChip.kt
  feature/explore/src/main/java/com/napzak/market/explore/state/ExploreUiState.kt
  feature/store/build.gradle.kts
  feature/store/src/main/java/com/napzak/market/store/component/GenreFilterChip.kt
  feature/store/src/main/java/com/napzak/market/store/component/StoreBottomSheetScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/store/state/StoreUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#156 [FEAT/#144] 장르상세 API 연동
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/state/GenreDetailUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#158 [UI/#36] 스플래쉬 뷰 구현
  app/src/main/res/values/themes.xml
  core/designsystem/src/main/res/drawable/ic_logo.xml
  core/designsystem/src/main/res/drawable/img_sample.png
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/splash/.gitignore
  feature/splash/build.gradle.kts
  feature/splash/proguard-rules.pro
  feature/splash/src/main/AndroidManifest.xml
  feature/splash/src/main/java/com/napzak/market/splash/SplashScreen.kt
  feature/splash/src/main/java/com/napzak/market/splash/navigation/SplashNavigator.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: UI :iphone:, 멀린연진 :angel:

#139 [FEAT/#127] 설정페이지 기능구현
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/model/SettingViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/navigation/SettingsNavigation.kt
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#160 [Feat/#134] 약관동의 온보딩 기능 구현
  data/store/src/main/java/com/napzak/market/store/datasource/StoreDataSource.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/TermsResponse.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreMapper.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/StoreRepositoryImpl.kt
  data/store/src/main/java/com/napzak/market/store/service/StoreService.kt
  domain/store/src/main/java/com/napzak/market/store/model/TermsAgreement.kt
  domain/store/src/main/java/com/napzak/market/store/repository/StoreRepository.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/CheckTermsAgreementUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/SetTermsAgreementUseCase.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/model/TermsAgreementUiState.kt
Labels: FEAT :sparkles:, 멀린연진 :angel:

#157 [FEAT/#118] 물품 상세화면 로직 구현
  core/common/src/main/java/com/napzak/market/common/type/TradeStatusType.kt
  data/product/src/main/java/com/napzak/market/product/dto/ProductGetDetailResponse.kt
  data/product/src/main/java/com/napzak/market/product/mapper/ProductDetailMapper.kt
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductImageGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationBuyGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductMarketGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/ProductDetail.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/ProductPhoto.kt
  feature/detail/src/main/java/com/napzak/market/detail/model/StoreInfo.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: FEAT :sparkles:, 암살자석준 :rage:

#159 [FEAT/#121] 탈퇴화면 로직 구현
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutSideEffect.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/SignOutViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/navigation/SignOutNavigation.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#163 [UI/#35] 로그인 뷰 구현
  core/designsystem/src/main/res/drawable/ic_kakao_logo.xml
  core/designsystem/src/main/res/raw/lottie_login.json
  feature/login/.gitignore
  feature/login/build.gradle.kts
  feature/login/proguard-rules.pro
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/napzak/market/login/LoginScreen.kt
  feature/login/src/main/java/com/napzak/market/login/LoginViewModel.kt
  feature/login/src/main/java/com/napzak/market/login/component/KakaoLoginButton.kt
  feature/login/src/main/java/com/napzak/market/login/navigation/LoginNavigator.kt
  feature/login/src/main/res/values/strings.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: UI :iphone:, 멀린연진 :angel:

#161 [FEAT/#145] 검색화면 API 연동
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/search/build.gradle.kts
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
  feature/search/src/main/java/com/napzak/market/search/SearchViewModel.kt
  feature/search/src/main/java/com/napzak/market/search/state/SearchUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#164 [FEAT/#153] 물품 수정 등록 API 연동, 장르 추가 요청 로직 구현
  domain/registration/src/main/java/com/napzak/market/registration/usecase/EditRegisteredProductUseCase.kt
  domain/registration/src/main/java/com/napzak/market/registration/usecase/GetRegisteredPurchaseProductUseCase.kt
  domain/registration/src/main/java/com/napzak/market/registration/usecase/GetRegisteredSaleProductUseCase.kt
  feature/registration/src/main/java/com/napzak/market/registration/RegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/PhotoPicker.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/GenreSearchScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/component/GenreSearchEmptyView.kt
  feature/registration/src/main/java/com/napzak/market/registration/model/Photo.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#162 [FEAT/#146] 마켓페이지 API 연동
  data/product/src/main/java/com/napzak/market/product/service/ProductExploreService.kt
  data/product/src/main/java/com/napzak/market/product/service/ProductStoreService.kt
  domain/product/build.gradle.kts
  domain/product/src/main/java/com/napzak/market/product/model/ExploreParameters.kt
  domain/product/src/main/java/com/napzak/market/product/usecase/GetStoreProductsUseCase.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/model/MyPageViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/state/MyPageUiState.kt
  feature/store/build.gradle.kts
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/store/state/StoreOptionState.kt
  feature/store/src/main/java/com/napzak/market/store/store/state/StoreUiState.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#172 [FIX/#169] ProductPhotoResponse dto 수정
  data/product/src/main/java/com/napzak/market/product/dto/ProductGetDetailResponse.kt
Labels: FIX :hammer:, 암살자석준 :rage:

#165 [FEAT/#120] 프로필 수정 기능 구현
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/type/PhotoType.kt
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/UploadStorePhotoUseCase.kt
  feature/store/build.gradle.kts
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/state/EditStoreUiState.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#171 [FEAT/#170] 화면 간 navigation 연결
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/navigation/ProductDetailNavigation.kt
  feature/explore/src/main/java/com/napzak/market/explore/navigation/ExploreNavigation.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/navigation/StoreNavigation.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#177 [FEAT/#167] 마이페이지 UI 보강
  feature/main/src/main/java/com/napzak/market/main/MainActivity.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingSideEffect.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/SettingsScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/setting/model/SettingViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/signout/navigation/SignOutNavigation.kt
Labels: FEAT :sparkles:, MOD ✅, 암살자석준 :rage:

#179 [REFACTOR/#178] 프로젝트 전체에 걸친 UI 수정
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreDetailResponse.kt
  data/store/src/main/java/com/napzak/market/store/dto/response/StoreEditProfileResponse.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreDetailMapper.kt
  data/store/src/main/java/com/napzak/market/store/mapper/StoreEditProfileMapper.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationBuyGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductInformationSellGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/component/group/ProductMarketGroup.kt
  feature/detail/src/main/java/com/napzak/market/detail/navigation/ProductDetailNavigation.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/report/src/main/java/com/napzak/market/report/navigation/ReportNavigation.kt
  feature/splash/src/main/java/com/napzak/market/splash/navigation/SplashNavigator.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreSideEffect.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/navigation/EditStoreNavigation.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
Labels: MOD ✅, REFACTOR :recycle:, 암살자석준 :rage:

#182 [Feat/#180] 카카오 소셜 로그인 웹뷰로 연결 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/napzak/market/login/LoginKakaoLauncher.kt
  feature/login/src/main/java/com/napzak/market/login/LoginScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
Labels: FEAT :sparkles:, 멀린연진 :angel:

#185 [FEAT/#183] 메인화면들에 BackHandler 추가
  feature/explore/src/main/java/com/napzak/market/explore/navigation/ExploreNavigation.kt
  feature/home/src/main/java/com/napzak/market/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/napzak/market/main/MainNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
Labels: FEAT :sparkles:, 암살자석준 :rage:

#189 [FIX/#188] 마이페이지 아이콘 수정
  core/designsystem/src/main/res/drawable/ic_favorite_27.xml
  core/designsystem/src/main/res/drawable/ic_favorite_36.xml
  core/designsystem/src/main/res/drawable/ic_help_32.xml
  core/designsystem/src/main/res/drawable/ic_help_36.xml
  core/designsystem/src/main/res/drawable/ic_purchase_32.xml
  core/designsystem/src/main/res/drawable/ic_purchase_36.xml
  core/designsystem/src/main/res/drawable/ic_recent_30.xml
  core/designsystem/src/main/res/drawable/ic_recent_36.xml
  core/designsystem/src/main/res/drawable/ic_sales_32.xml
  core/designsystem/src/main/res/drawable/ic_sales_36.xml
  core/designsystem/src/main/res/drawable/ic_settings_27.xml
  core/designsystem/src/main/res/drawable/ic_settings_36.xml
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageMenu.kt
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#190 [UI/#174] 로그인 및 온보딩 간격 조정
  domain/store/src/main/java/com/napzak/market/store/model/KakaoLogin.kt
  feature/login/src/main/java/com/napzak/market/login/LoginViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/termsAgreement/TermsAgreementScreen.kt
Labels: UI :iphone:, 멀린연진 :angel:

#201 [Refactor/#175] 닉네임 검증 로직 추가 및 UseCase 분리
  domain/store/src/main/java/com/napzak/market/store/model/NicknameValidationResult.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/ValidateNicknameUseCase.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameValidationResultExt.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/NicknameViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameErrorType.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameUiState.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/nickname/model/NicknameValidationResult.kt
  feature/onboarding/src/main/res/values/strings.xml
Labels: REFACTOR :recycle:, 멀린연진 :angel:

#193 [FIX/#192] 1차 QA 홈 관련 수정
  feature/home/src/main/java/com/napzak/market/home/component/HorizontalScrollableProducts.kt
  feature/home/src/main/java/com/napzak/market/home/component/VerticalGridProducts.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/res/values/strings.xml
Labels: FIX :hammer:, 암살자석준 :rage:

#196 [FIX/#191] 1차 QA 물품 상세 관련 수정
  core/util/src/main/java/com/napzak/market/util/android/SnackBarController.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailScreen.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailSideEffect.kt
  feature/detail/src/main/java/com/napzak/market/detail/ProductDetailViewModel.kt
  feature/detail/src/main/res/values/strings.xml
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/main/src/main/java/com/napzak/market/main/component/MainSnackBarHost.kt
  feature/report/src/main/java/com/napzak/market/report/state/ReportState.kt
Labels: FIX :hammer:, 암살자석준 :rage:

#206 [FIX/#197] 마켓상세 QA
  core/common/src/main/java/com/napzak/market/common/type/MarketTab.kt
Labels: FIX :hammer:, 충신채린 :saluting_face:

#209 [FIX/#181] 장르바텀시트 QA
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/GenreListItem.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/bottomsheet/GenreSearchBottomSheet.kt
Labels: FIX :hammer:, 충신채린 :saluting_face:

#211 [FIX/#199] 탐색,장르,마켓 QA
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/GenreFilterChip.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/explore/src/main/java/com/napzak/market/explore/ExploreScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/ExploreViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/component/GenreNavigationButton.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailScreen.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/GenreDetailViewModel.kt
  feature/explore/src/main/java/com/napzak/market/explore/genredetail/state/GenreDetailUiState.kt
  feature/explore/src/main/java/com/napzak/market/explore/state/ExploreUiState.kt
  feature/explore/src/main/res/values/string.xml
  feature/store/src/main/java/com/napzak/market/store/component/GenreChip.kt
  feature/store/src/main/java/com/napzak/market/store/component/GenreFilterChip.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/store/StoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/store/state/StoreUiState.kt
  feature/store/src/main/res/values/strings.xml
Labels: FIX :hammer:, 충신채린 :saluting_face:

#204 [Refactor/#202] 장르온보딩 장르칩 정렬 수정
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreViewModel.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreEvent.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/model/GenreUiState.kt
Labels: REFACTOR :recycle:, 멀린연진 :angel:

#208 [FIX/#200] 검색화면 QA
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/SearchTextField.kt
  feature/search/src/main/java/com/napzak/market/search/SearchScreen.kt
  feature/search/src/main/java/com/napzak/market/search/component/GenreNavigationButtton.kt
  feature/search/src/main/res/drawable/ic_search_12.xml
Labels: FIX :hammer:, 충신채린 :saluting_face:

#213 [Chore/#212] 로그인 로띠 변경
  core/designsystem/src/main/res/raw/lottie_login.json
  core/util/src/main/java/com/napzak/market/util/android/NapzakShadowExt.kt
  core/util/src/main/java/com/napzak/market/util/android/model/ShadowDirection.kt
  feature/login/src/main/java/com/napzak/market/login/LoginScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/GenreScreen.kt
  feature/onboarding/src/main/java/com/napzak/market/onboarding/genre/component/GenreGridList.kt
Labels: CHORE :chains:, 멀린연진 :angel:

#205 [FIX/#187] 1차 QA 프로필 편집 관련 수정
  domain/presigned-url/src/main/java/com/napzak/market/presigned_url/usecase/UploadStorePhotoUseCase.kt
  domain/store/src/main/java/com/napzak/market/store/type/NicknameValidationErrorType.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/ValidateNicknameUseCase.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreScreen.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/EditStoreViewModel.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStoreContainer.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStoreDescriptionSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStoreNickNameSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStorePhotoSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/component/EditStorePreferredGenreSection.kt
  feature/store/src/main/java/com/napzak/market/store/edit_store/state/EditStoreUiState.kt
  feature/store/src/main/res/values/strings.xml
Labels: FIX :hammer:, REFACTOR :recycle:, 암살자석준 :rage:

#194 [FIX/#186] 등록 화면 1차 QA 반영
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/component/RegistrationViewGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/GenreSearchScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/genre/component/GenreSearchHeader.kt
  feature/registration/src/main/java/com/napzak/market/registration/navigation/RegistrationNavigation.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/PurchaseRegistrationViewModel.kt
  feature/registration/src/main/java/com/napzak/market/registration/purchase/component/PriceNegotiationGroup.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationScreen.kt
  feature/registration/src/main/java/com/napzak/market/registration/sale/SaleRegistrationViewModel.kt
Labels: FIX :hammer:, 퍼시벌종명 :sunglasses:

#210 [FIX/#195] 마이페이지 이슈 해결
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/component/MyPageProfileSection.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/model/MyPageViewModel.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/napzak/market/mypage/state/MyPageUiState.kt
Labels: FIX :hammer:, 모드레드재원 :imp:

#214 [Feat/#176] 자동로그인 구현
  data/store/src/main/java/com/napzak/market/store/di/RepositoryModule.kt
  data/store/src/main/java/com/napzak/market/store/repositoryimpl/TokenProviderImpl.kt
  domain/store/src/main/java/com/napzak/market/store/repository/TokenProvider.kt
  domain/store/src/main/java/com/napzak/market/store/usecase/CheckAutoLoginUseCase.kt
  feature/login/src/main/java/com/napzak/market/login/navigation/LoginNavigator.kt
  feature/main/src/main/java/com/napzak/market/main/MainScreen.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/java/com/napzak/market/splash/SplashScreen.kt
  feature/splash/src/main/java/com/napzak/market/splash/SplashViewModel.kt
  feature/splash/src/main/java/com/napzak/market/splash/navigation/SplashNavigator.kt
Labels: FEAT :sparkles:, 멀린연진 :angel:

#223 [REFACTOR/#221] 장르칩 중앙정렬
  feature/store/src/main/java/com/napzak/market/store/store/StoreScreen.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:
