Repository napzakmarket/Napzak-Android, pull requests merged in 2025-03, with the labels that each got.

#4 [ADD/#3] 프로젝트 디자인시스템 세팅
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/pretendard_bold.otf
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
Labels: ADD ➕, 퍼시벌종명 :sunglasses:

#19 [CHORE/#12] 색상 코드 추가
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Color.kt
Labels: CHORE :chains:, 퍼시벌종명 :sunglasses:

#18 [UI/#11] SnackBar 공통 컴포넌트 및 SnackBar 구현
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/CommonSnackBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/HeartClickSnackBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/WarningSnackBar.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_check_snackbar_18.xml
  core/designsystem/src/main/res/drawable/ic_delete_snackbar_16.xml
  core/designsystem/src/main/res/drawable/ic_heartclick_snackbar_12.xml
  core/designsystem/src/main/res/drawable/ic_warning_snackbar_12.xml
  core/designsystem/src/main/res/values/strings.xml
Labels: UI :iphone:, 모드레드재원 :imp:

#13 [UI/#5] 공통 컴포넌트 (TextField 구현)
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/InputTextField.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/NapzakDefaultTextField.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/textfield/SearchTextField.kt
  core/designsystem/src/main/res/drawable/ic_cancel_search_12.xml
  core/designsystem/src/main/res/drawable/ic_search_12.xml
Labels: UI :iphone:, 퍼시벌종명 :sunglasses:

#21 [ADD/#20] ENUM 클래스 추가
  core/common/src/main/java/com/napzak/market/common/type/RoleType.kt
  core/common/src/main/java/com/napzak/market/common/type/TradeStatusType.kt
  core/designsystem/src/main/java/com/napzak/market/designsystem/component/productItem/NapzakLargeProductItem.kt
Labels: ADD ➕, FIX :hammer:, 암살자석준 :rage:
